development:
  adapter: postgresql
  database: your_database_name_development
  username: your_postgres_user
  password: your_postgres_password
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: your_database_name_test
  username: your_postgres_user
  password: your_postgres_password
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: your_database_name_production
  username: your_postgres_user
  password: your_postgres_password
  host: localhost
  pool: 5
  timeout: 5000
